export const COFFEE_INCREASE = "COFFEE_INCREASE";
export const COFFEE_DECREASE = "COFFEE_DECREASE";
export const TREATS_INCREASE = "TREATS_INCREASE";
export const TREATS_DECREASE = "TREATS_DECREASE";
export const REMOVE = "REMOVE";
export const CLEAR_CART  = "CLEAR_CART";
export const GET_TOTAL = "GET_TOTAL";
export const GET_AMOUNT = "GET_AMOUNT";
